import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const AppFont = Noto_Sans({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Noto_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Noto_Sans({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en">
      <body className={AppFont.className}>{children}</body>
    </html>
  );
}
